#define ANNEALING_FLOAT_CMP_THRESHOLD						0.0001
//#define ANNEALING_STOP_TEMP_OVERRIDE						499.0

#define SANITY_CHECK_CELL_FUNC_WIDTH						3
#define SANITY_CHECK_CELL_FUNC_HEIGHT						3
#define SANITY_CHECK_CELL_IO_RING_DEPTH						1
#define SANITY_CHECK_CONNECTIONS_NUM_PER_IO_CELL			1
#define SANITY_CHECK_CONNECTIONS_AVG_NUM_PER_FUNC_CELL		3.5

#define SANITY_CHECK_ANNEALING_START_TEMP					150.0
#define SANITY_CHECK_ANNEALING_SCHEDULE						-0.5
#define SANITY_CHECK_ANNEALING_TIMEOUT						10

#define COMPLEXITY_TEST_IO_RING_DEPTH						1
#define COMPLEXITY_TEST_MAX_SIZE_BRUTEFORCE					12
#define COMPLEXITY_TEST_MAX_SIZE_ANNEALING					100
#define COMPLEXITY_TEST_RETRIES								3
#define COMPLEXITY_TEST_CONNECTIONS_NUM_PER_IO_CELL			1
#define COMPLEXITY_TEST_CONNECTIONS_AVG_NUM_PER_FUNC_CELL	3.5
#define COMPLEXITY_TEST_START_TEMPERATURE					500.0
#define COMPLEXITY_TEST_SCHEDULE							-0.05
#define COMPLEXITY_TEST_TIMEOUT								10

#define SCHEDULE_TEST_IO_RING_DEPTH							1
#define SCHEDULE_TEST_START_TEMPERATURE						500.0
#define SCHEDULE_TEST_START_SCHEDULE						-50.0
#define SCHEDULE_TEST_STOP_SCHEDULE							-0.01
#define SCHEDULE_TEST_CONNECTIONS_NUM_PER_IO_CELL			1
#define SCHEDULE_TEST_CONNECTIONS_AVG_NUM_PER_FUNC_CELL		3.5
#define SCHEDULE_TEST_RETRIES								5
#define SCHEDULE_TEST_TIMEOUT								10

#define LARGE_TEST_CELL_FUNC_WIDTH							50
#define LARGE_TEST_CELL_FUNC_HEIGHT							50
#define LARGE_TEST_IO_RING_DEPTH							1
#define LARGE_TEST_CONNECTIONS_NUM_PER_IO_CELL				1
#define LARGE_TEST_CONNECTIONS_AVG_NUM_PER_FUNC_CELL		3.5
#define LARGE_TEST_START_TEMPERATURE						500.0
#define LARGE_TEST_SCHEDULE									-0.05
#define LARGE_TEST_TIMEOUT									10
