//#define DEBUG
//#define EXTRA_DEBUG
//#define DEBUG_CONNECTION_COUNT
//#define CONNECTION_THRESHOLD

#define ENABLE_SANITY_CHECK
#define ENABLE_BRUTEFORCE_COMPLEXITY_TEST
#define ENABLE_ANNEALING_SCHEDULE_TEST_3x3
#define ENABLE_ANNEALING_SCHEDULE_TEST_10x10
#define ENABLE_ANNEALING_COMPLEXITY_TEST
//#define ENABLE_LARGE_TEST

#define ENABLE_BRUTEFORCE_DISOPTIMUM
//#define ENABLE_BRUTEFORCE_DISOPTIMUM_PRINTOUT
#define ENABLE_BRUTEFORCE_OPTIMUM_COUNT
//#define ENABLE_ANNEALING_BEFORE_AFTER_PRINTOUT

#define SANITY_CHECK_PRINTOUT_CHIPS
#define SANITY_CHECK_ENABLE_BRUTEFORCE
#define SANITY_CHECK_ENABLE_ANNEALING
