//#define DEBUG
//#define EXTRA_DEBUG

#define ENABLE_BRUTEFORCE_DISOPTIMUM
//#define ENABLE_BRUTEFORCE_DISOPTIMUM_PRINTOUT
//#define ENABLE_BRUTEFORCE_OPTIMUM_COUNT
//#define SANITY_CHECK_PRINTOUT_CHIPS
#define SANITY_CHECK_ENABLE_BRUTEFORCE
#define SANITY_CHECK_ENABLE_ANNEALING
